import httpx
from typing import List
from app.models.db_models import ChatHistory, Message, LabReport

async def generate_ai_response(
    session_id: str, 
    user_message: str, 
    user_email: str, 
    patient_context: str = ""
) -> str:
    # 1. Fetch all LabReport documents for this user from MongoDB
    reports: List[LabReport] = await LabReport.find(LabReport.user_email == user_email).to_list()
    
    extracted_reports_text = ""
    if reports:
        report_blocks = []
        for r in reports:
            # Format structured biomarkers into readable lines
            biomarker_lines = "\n".join(
                [f"  - {b.metric}: {b.value} {b.unit} (Status: {b.status}, Confidence: {b.confidence})" for b in r.biomarkers]
            ) if r.biomarkers else "  No structured biomarkers extracted."

            # Build a clear block per lab report
            block = (
                f"--- Lab Report: {r.filename} (Uploaded: {r.upload_date.strftime('%Y-%m-%d')}) ---\n"
                f"Status: {r.status}\n"
                f"Extracted Snippet:\n{r.extracted_text_snippet}\n"
                f"Key Biomarkers:\n{biomarker_lines}"
            )
            report_blocks.append(block)
            
        extracted_reports_text = "\n\n".join(report_blocks)

    # Fallback context if no reports are found in MongoDB
    context_to_use = extracted_reports_text if extracted_reports_text else patient_context
    if not context_to_use.strip():
        context_to_use = "No medical lab reports found in the database for this user."

    # 2. Fetch or initialize chat history in MongoDB
    chat_session = await ChatHistory.find_one(ChatHistory.session_id == session_id)
    if not chat_session:
        chat_session = ChatHistory(session_id=session_id, messages=[])

    # 3. Append user message to database history
    chat_session.messages.append(Message(role="user", content=user_message))
    await chat_session.save()

    # 4. Construct system prompt containing actual lab data
    system_prompt = f"""You are CuraTwin's clinical AI assistant.
You have access to the patient's actual lab reports and extracted biomarkers from their Medical Vault.
Analyze this context directly to answer the user's question accurately and professionally. Do not ask for patient IDs or MRNs if context is provided below.

=== PATIENT LAB CONTEXT FROM VAULT ===
{context_to_use}
======================================

USER QUESTION:
{user_message}
"""

    # 5. Query local Ollama instance
    try:
        async with httpx.AsyncClient() as client:
            response = await client.post(
                "http://localhost:11434/api/generate",
                json={
                    "model": "llama3",
                    "prompt": system_prompt,
                    "stream": False
                },
                timeout=60.0
            )
            response.raise_for_status()
            data = response.json()
            ai_reply = data.get("response", "Error: No response generated by model.")
            
    except Exception as e:
        print(f"❌ Ollama Connection Error: {str(e)}")
        ai_reply = "I am currently offline. Please ensure the local Ollama engine is running."

    # 6. Save assistant response to database history
    chat_session.messages.append(Message(role="assistant", content=ai_reply))
    await chat_session.save()

    return ai_reply